### ISSUE TITLE
Stocks are too undervalued, they need to be higher, and maybe have a higher minimum price over time

### ISSUE THREAD

**Issue by E1337Kat** [SunDwarf/Jokusoramame#14]
https://github.com/SunDwarf/Jokusoramame/blob/master/joku/cogs/games/stocks.py#L148

**Comment by jundis** [comment]
I think the best way to do it would be to have varied minimum prices, and have them hit the minimum less often. It's super easy to just wait until things are $2, then give it a day and sell at $15. Rinse and repeat.

By having 5 stocks start at 2, 5 stocks at 10, 5 stocks at 25, 5 stocks at 50 (etc or similar) you would have a growth pattern to it.

The limit, as well as share total, of the lower cost stocks should be adjusted as well. I should not be able to buy 100% of the stock, but having nearly $10,000 made me dump all my money into $2 stocks and lose tax on the $6.5k I have left because buying in at $8 a stock when it could crash to $2 at any time is just a bad idea.

**Comment by SunDwarf** [comment]
PRs welcome

**Comment by Fuyukai** [comment]
Apart from the shitty circlejerk response, I don't really know how to make any of the stock logic better. Right now it's all completely randomized, which I want to change.

Even taking into account your suggestion, because it's 100% random it can easily fuck up and crash instantly to the minimum, and hover around there. I'd be open to figuring out a way to make them grow organically rather than randomly.

**Comment by E1337Kat** [comment]
Rewrite makes issue invalid.
